### ISSUE TITLE
Allow for Nested Sealed Class

### ISSUE THREAD

**Issue by thegarlynch** [ZacSweers/MoshiX#23] opened 2020-05-13 17:59 UTC
I always though this already a default implementation.. but somehow it is not..

**Comment by ZacSweers** [comment] 2020-05-13 18:51
Can you be more specific?

**Comment by thegarlynch** [comment] 2020-05-13 18:58
Sorry. I was trying to do this because i thought it is implemented already

```kotlin

@JsonClass(generateAdapter = true, generator = "sealed:shape")
sealed class Shape(){

      @TypeLabel("circle")
      @JsonClass(generateAdapter = true)
      data class Circle(val name : String) : Shape()

      sealed class Rectangle() {

         @TypeLabel("regular_rectangle")
         @JsonClass(generateAdapter = true)
         data class Regular(val name : String) : Rectangle()

         @TypeLabel("rounded_rectangle")
         @JsonClass(generateAdapter = true)
         data class Rounded(val name : String) : Rectangle()

      }

}

**Comment by ZacSweers** [comment] 2020-08-06 18:02
Rectangle should be annotated too. What trace do you get with that?

**Comment by ZacSweers** [comment] 2020-10-12 05:24
Closing, feel free to comment again if the above does not resolve it

**Closed by ZacSweers** 2020-10-12 05:24 UTC

**Comment by paulblessing** [comment] 2020-11-02 22:35
Just had a similar sealed class hierarchy fail at runtime. Can reproduce using a slight variation on OP's code, assuming this is the way Rectangle was suggested to be annotated:

```kotlin
@JsonClass(generateAdapter = true, generator = "sealed:shape")
sealed class Shape {

  @TypeLabel("circle")
  @JsonClass(generateAdapter = true)
  data class Circle(val name: String) : Shape()

  @TypeLabel("rectangle")
  @JsonClass(generateAdapter = true, generator = "sealed:rectangle_type")
  sealed class Rectangle : Shape() {

    @TypeLabel("regular_rectangle")
    @JsonClass(generateAdapter = true)
    data class Regular(val name: String) : Rectangle()

    @TypeLabel("rounded_rectangle")
    @JsonClass(generateAdapter = true)
    data class Rounded(val name: String) : Rectangle()

  }

}
```

and then this test case

```kotlin
class ShapeTest {

  @Test fun shapes() {
    val moshi = Moshi.Builder().build()
    val adapter = moshi.adapter<List<Shape>>()

    val shapes = listOf(
        Shape.Circle("circle"),
        Shape.Rectangle.Regular("regular"),
        Shape.Rectangle.Rounded("rounded")
    )

    val jsonString = adapter.toJson(shapes)
  }

}
```

fails with

```
java.lang.IllegalArgumentException: Expected one of [class com.example.Shape$Circle, class com.example.Shape$Rectangle] but found Regular(name=regular), a class com.example.Shape$Rectangle$Regular. Register this subtype.

	at com.squareup.moshi.adapters.PolymorphicJsonAdapterFactory$PolymorphicJsonAdapter.toJson(PolymorphicJsonAdapterFactory.java:286)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
	at com.example.ShapeJsonAdapter.toJson(ShapeJsonAdapter.kt:27)
	at com.example.ShapeJsonAdapter.toJson(ShapeJsonAdapter.kt:13)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
	at com.squareup.moshi.CollectionJsonAdapter.toJson(CollectionJsonAdapter.java:91)
	at com.squareup.moshi.CollectionJsonAdapter$2.toJson(CollectionJsonAdapter.java:55)
	at com.squareup.moshi.internal.NullSafeJsonAdapter.toJson(NullSafeJsonAdapter.java:50)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:62)
	at com.squareup.moshi.JsonAdapter.toJson(JsonAdapter.java:69)
	at com.example.ShapeTest.shapes(ShapeTest.kt:19)
...
```

**Comment by ZacSweers** [comment] 2020-11-02 22:41
That's a tricky one and not really an issue with Moshi sealed. It would fail in normal moshi too, because you're telling it you have a list of `Shape` types and moshi will use `ShapeJsonAdapter` for _every_ element when your elements should actually be treated as heterogenous types with potentially different adapters. You should either make a custom `JsonAdapter.Factory` for delegating to the right subtype or your own list adapter that individually gets an adapter for each element type (would only work for Classes and not parameterized types).

**Comment by ZacSweers** [comment] 2020-11-02 22:42
There might be a way for moshi-sealed to work with it, but I think it would be error-prone because it would require sealed subtypes all the way down to know for sure. Would also be quite a headache with incremental processing where one type change shakes all of them

**Comment by paulblessing** [comment] 2020-11-02 22:43
Makes sense, thanks for filling in what I was probably not thinking. Agreed that it's a tricky one.
