### ISSUE TITLE
Sealed class hierarchy error

### ISSUE THREAD

**Issue by rddsantos** [ZacSweers/MoshiX#69] opened 2020-12-10 12:35 UTC
Hey, I’m trying to have a sealed class inside another sealed class, like described bellow and it throws the following error:

**error: Missing @TypeLabel public abstract class StrawBerry extends Fruit**

Example:
@JsonClass(generateAdapter = true, generator = "sealed:type")
sealed class Fruit

sealed class Strawberry: Fruit()

@TypeLabel("a")
@JsonClass(generateAdapter = true)
data class SmallStrawberry: Strawberry()

@TypeLabel("b")
@JsonClass(generateAdapter = true)
data class BigStrawberry: Strawberry()

Am I doing something wrong or is this not supported at the moment?

**Comment by ZacSweers** [comment] 2020-12-10 15:53
What's the expected behavior?

**Comment by ZacSweers** [comment] 2020-12-22 19:20
Closing due to lack of information, feel free to revisit with an answer to the above

**Closed** 2020-12-22 19:20 UTC
