### ISSUE TITLE
Custom Annotations require Retention value to be set

### ISSUE THREAD

**Issue by chrisjenx** [ZacSweers/MoshiX#119] opened 2021-05-27 21:41 UTC
We use some custom annotations on our Json classes, KSP was failing until we provided a value for `@Retention` on those annotation definitions. (TBH, it's probably KSP not reading and providing the default retention value)

e.g:
```kotlin
@JsonQualifier
@Retention
@MustBeDocumented
annotation class LocalDateOnly
```

was changed to:

```kotlin
@JsonQualifier
@Retention(AnnotationRetention.RUNTIME)
@MustBeDocumented
annotation class LocalDateOnly
```

Stacktrace and example class  for completeness

```kotlin
@Parcelize
@JsonClass(generateAdapter = true)
data class IdentificationParsingData(
    @Json(name = "id_number")
    val number: String?,
    @Json(name = "name")
    val fullName: String?,
    @Json(name = "date_of_birth")
    @LocalDateOnly val dob: Date?,
) : Parcelable
```

```
e: [ksp] java.lang.IllegalStateException: No value found for value. Was null
        at dev.zacsweers.moshix.ksp.MoshiApiUtilKt.generator(MoshiApiUtil.kt:155)
        at dev.zacsweers.moshix.ksp.JsonClassSymbolProcessor.adapterGenerator(JsonClassSymbolProcessorProvider.kt:171)
        at dev.zacsweers.moshix.ksp.JsonClassSymbolProcessor.process(JsonClassSymbolProcessorProvider.kt:119)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:172)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:171)
```

**Comment by ZacSweers** [comment] 2021-05-31 19:55
I reproduced and I believe this is a bug in KSP because it's reporting a null annotation value, which isn't legal. Filed here https://github.com/google/ksp/issues/463

**Comment by ZacSweers** [comment] 2021-08-19 20:48
This should be fixed upstream now

**Closed by ZacSweers** 2021-08-19 20:48 UTC
Labels: Upstream KSP Bug
